/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maintenance.service;

import java.awt.Color;

/**
 *
 * @author yusri
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKiri = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Menu1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        pnMenu1 = new javax.swing.JPanel();
        Menu2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DataMekanik = new javax.swing.JLabel();
        pnMenu2 = new javax.swing.JPanel();
        Menu3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DataMesin = new javax.swing.JLabel();
        pnMenu3 = new javax.swing.JPanel();
        Menu4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        DataPerbaikan = new javax.swing.JLabel();
        pnMenu5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Menu5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        DataKaryawan = new javax.swing.JLabel();
        pnMenu6 = new javax.swing.JPanel();
        pnMenu4 = new javax.swing.JPanel();
        pnKanan = new javax.swing.JPanel();
        mainContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnKiri.setBackground(new java.awt.Color(255, 255, 255));
        pnKiri.setMinimumSize(new java.awt.Dimension(300, 768));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/logo2.png"))); // NOI18N

        Menu1.setBackground(new java.awt.Color(255, 255, 255));
        Menu1.setPreferredSize(new java.awt.Dimension(300, 60));
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu1MouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/home.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setAlignmentY(0.4F);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
        });

        pnMenu1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnMenu1Layout = new javax.swing.GroupLayout(pnMenu1);
        pnMenu1.setLayout(pnMenu1Layout);
        pnMenu1Layout.setHorizontalGroup(
            pnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnMenu1Layout.setVerticalGroup(
            pnMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu1Layout = new javax.swing.GroupLayout(Menu1);
        Menu1.setLayout(Menu1Layout);
        Menu1Layout.setHorizontalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addComponent(pnMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu1Layout.setVerticalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dashboard))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(pnMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu2.setBackground(new java.awt.Color(255, 255, 255));
        Menu2.setPreferredSize(new java.awt.Dimension(300, 60));
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/mekanik.png"))); // NOI18N
        jLabel3.setText("jLabel2");

        DataMekanik.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DataMekanik.setText("Data Mekanik");
        DataMekanik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMekanikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataMekanikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataMekanikMouseExited(evt);
            }
        });

        pnMenu2.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu2.setPreferredSize(new java.awt.Dimension(9, 0));

        javax.swing.GroupLayout pnMenu2Layout = new javax.swing.GroupLayout(pnMenu2);
        pnMenu2.setLayout(pnMenu2Layout);
        pnMenu2Layout.setHorizontalGroup(
            pnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnMenu2Layout.setVerticalGroup(
            pnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu2Layout = new javax.swing.GroupLayout(Menu2);
        Menu2.setLayout(Menu2Layout);
        Menu2Layout.setHorizontalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addComponent(pnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu2Layout.setVerticalGroup(
            Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(Menu2Layout.createSequentialGroup()
                .addGroup(Menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DataMekanik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Menu3.setBackground(new java.awt.Color(255, 255, 255));
        Menu3.setPreferredSize(new java.awt.Dimension(300, 60));
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu3MouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/messin.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        DataMesin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DataMesin.setText("Data Mesin");
        DataMesin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMesinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataMesinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataMesinMouseExited(evt);
            }
        });

        pnMenu3.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu3.setPreferredSize(new java.awt.Dimension(9, 0));

        javax.swing.GroupLayout pnMenu3Layout = new javax.swing.GroupLayout(pnMenu3);
        pnMenu3.setLayout(pnMenu3Layout);
        pnMenu3Layout.setHorizontalGroup(
            pnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnMenu3Layout.setVerticalGroup(
            pnMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu3Layout = new javax.swing.GroupLayout(Menu3);
        Menu3.setLayout(Menu3Layout);
        Menu3Layout.setHorizontalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu3Layout.createSequentialGroup()
                .addComponent(pnMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataMesin)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        Menu3Layout.setVerticalGroup(
            Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(Menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataMesin))
                .addContainerGap(9, Short.MAX_VALUE))
            .addComponent(pnMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Menu4.setBackground(new java.awt.Color(255, 255, 255));
        Menu4.setPreferredSize(new java.awt.Dimension(300, 60));
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu4MouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/perbaikan.png"))); // NOI18N
        jLabel9.setText("jLabel2");

        DataPerbaikan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DataPerbaikan.setText("Data Perbaikan");
        DataPerbaikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPerbaikanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataPerbaikanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataPerbaikanMouseExited(evt);
            }
        });

        pnMenu5.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu5.setPreferredSize(new java.awt.Dimension(9, 0));

        javax.swing.GroupLayout pnMenu5Layout = new javax.swing.GroupLayout(pnMenu5);
        pnMenu5.setLayout(pnMenu5Layout);
        pnMenu5Layout.setHorizontalGroup(
            pnMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnMenu5Layout.setVerticalGroup(
            pnMenu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu4Layout = new javax.swing.GroupLayout(Menu4);
        Menu4.setLayout(Menu4Layout);
        Menu4Layout.setHorizontalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu4Layout.createSequentialGroup()
                .addComponent(pnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataPerbaikan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu4Layout.setVerticalGroup(
            Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataPerbaikan))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(pnMenu5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Master Data");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Data Proses");

        Logout.setBackground(new java.awt.Color(19, 71, 186));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Keluar");
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Menu5.setBackground(new java.awt.Color(255, 255, 255));
        Menu5.setPreferredSize(new java.awt.Dimension(300, 60));
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu5MouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/karyawann.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        DataKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DataKaryawan.setText("Data Karyawan");
        DataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataKaryawanMouseExited(evt);
            }
        });

        pnMenu6.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu6.setPreferredSize(new java.awt.Dimension(9, 0));

        javax.swing.GroupLayout pnMenu6Layout = new javax.swing.GroupLayout(pnMenu6);
        pnMenu6.setLayout(pnMenu6Layout);
        pnMenu6Layout.setHorizontalGroup(
            pnMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        pnMenu6Layout.setVerticalGroup(
            pnMenu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu5Layout = new javax.swing.GroupLayout(Menu5);
        Menu5.setLayout(Menu5Layout);
        Menu5Layout.setHorizontalGroup(
            Menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu5Layout.createSequentialGroup()
                .addComponent(pnMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DataKaryawan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu5Layout.setVerticalGroup(
            Menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu5Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(Menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataKaryawan))
                .addContainerGap(9, Short.MAX_VALUE))
            .addComponent(pnMenu6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addComponent(Menu2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addComponent(Menu3, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addComponent(Menu4, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKiriLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnKiriLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnKiriLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(Menu5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Logo)
                .addGap(62, 62, 62)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(pnKiri, java.awt.BorderLayout.LINE_START);

        pnMenu4.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu4.setPreferredSize(new java.awt.Dimension(9, 0));

        javax.swing.GroupLayout pnMenu4Layout = new javax.swing.GroupLayout(pnMenu4);
        pnMenu4.setLayout(pnMenu4Layout);
        pnMenu4Layout.setHorizontalGroup(
            pnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1367, Short.MAX_VALUE)
        );
        pnMenu4Layout.setVerticalGroup(
            pnMenu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnMenu4, java.awt.BorderLayout.PAGE_START);

        pnKanan.setBackground(new java.awt.Color(204, 204, 255));
        pnKanan.setMinimumSize(new java.awt.Dimension(1066, 768));

        mainContent.setBackground(new java.awt.Color(74, 124, 237));
        mainContent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(19, 71, 186));
        jPanel1.setPreferredSize(new java.awt.Dimension(1046, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        mainContent.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnKananLayout = new javax.swing.GroupLayout(pnKanan);
        pnKanan.setLayout(pnKananLayout);
        pnKananLayout.setHorizontalGroup(
            pnKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKananLayout.setVerticalGroup(
            pnKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        Menu1.setBackground(new Color(240, 240, 240));
        pnMenu1.setBackground(new Color(19,71,186));
        mainContent.removeAll();
        mainContent.add(new menuDashboard());
        mainContent.repaint();
        mainContent.revalidate();
    }//GEN-LAST:event_DashboardMouseClicked

    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        Menu1.setBackground(new Color(240, 240, 240));
        pnMenu1.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        Menu1.setBackground(new Color(255, 255, 255));
        pnMenu1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DashboardMouseExited

    private void Menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseEntered
        Menu1.setBackground(new Color(240, 240, 240));
        pnMenu1.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_Menu1MouseEntered

    private void Menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseExited
        Menu1.setBackground(new Color(255, 255, 255));
        pnMenu1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Menu1MouseExited

    private void DataMekanikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMekanikMouseClicked
        Menu2.setBackground(new Color(240, 240, 240));
        pnMenu2.setBackground(new Color(19,71,186));
        mainContent.removeAll();
        mainContent.add(new menuMekanik());
        mainContent.repaint();
        mainContent.revalidate();
    }//GEN-LAST:event_DataMekanikMouseClicked

    private void DataMekanikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMekanikMouseEntered
        Menu2.setBackground(new Color(240, 240, 240));
        pnMenu2.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_DataMekanikMouseEntered

    private void DataMekanikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMekanikMouseExited
        Menu2.setBackground(new Color(255, 255, 255));
        pnMenu2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DataMekanikMouseExited

    private void Menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseEntered
        Menu2.setBackground(new Color(240, 240, 240));
        pnMenu2.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_Menu2MouseEntered

    private void Menu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseExited
        Menu2.setBackground(new Color(255, 255, 255));
        pnMenu2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Menu2MouseExited

    private void DataMesinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMesinMouseClicked
        Menu3.setBackground(new Color(240, 240, 240));
        pnMenu3.setBackground(new Color(19,71,186));
        mainContent.removeAll();
        mainContent.add(new menuMesin());
        mainContent.repaint();
        mainContent.revalidate();
    }//GEN-LAST:event_DataMesinMouseClicked

    private void DataMesinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMesinMouseEntered
        Menu3.setBackground(new Color(240, 240, 240));
        pnMenu3.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_DataMesinMouseEntered

    private void DataMesinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMesinMouseExited
        Menu3.setBackground(new Color(255, 255, 255));
        pnMenu3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DataMesinMouseExited

    private void Menu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseEntered
        Menu3.setBackground(new Color(240, 240, 240));
        pnMenu3.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_Menu3MouseEntered

    private void Menu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseExited
        Menu3.setBackground(new Color(255, 255, 255));
        pnMenu3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Menu3MouseExited

    private void DataPerbaikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPerbaikanMouseClicked
        Menu4.setBackground(new Color(240, 240, 240));
        pnMenu5.setBackground(new Color(19,71,186));
        mainContent.removeAll();
        mainContent.add(new menuPerbaikan());
        mainContent.repaint();
        mainContent.revalidate();
    }//GEN-LAST:event_DataPerbaikanMouseClicked

    private void DataPerbaikanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPerbaikanMouseEntered
        Menu4.setBackground(new Color(240, 240, 240));
        pnMenu5.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_DataPerbaikanMouseEntered

    private void DataPerbaikanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPerbaikanMouseExited
        Menu4.setBackground(new Color(255, 255, 255));
        pnMenu5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DataPerbaikanMouseExited

    private void Menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseEntered
        Menu4.setBackground(new Color(240, 240, 240));
        pnMenu5.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_Menu4MouseEntered

    private void Menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseExited
        Menu4.setBackground(new Color(255, 255, 255));
        pnMenu5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Menu4MouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Login  LoginFrame = new Login ();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void DataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataKaryawanMouseClicked
        Menu5.setBackground(new Color(240, 240, 240));
        pnMenu6.setBackground(new Color(19,71,186));
        mainContent.removeAll();
        mainContent.add(new menuKaryawan());
        mainContent.repaint();
        mainContent.revalidate();
    }//GEN-LAST:event_DataKaryawanMouseClicked

    private void DataKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataKaryawanMouseEntered
        Menu5.setBackground(new Color(240, 240, 240));
        pnMenu6.setBackground(new Color(19,71,186));
    }//GEN-LAST:event_DataKaryawanMouseEntered

    private void DataKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataKaryawanMouseExited
        Menu5.setBackground(new Color(255, 255, 255));
        pnMenu6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_DataKaryawanMouseExited

    private void Menu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu5MouseEntered

    private void Menu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel DataKaryawan;
    private javax.swing.JLabel DataMekanik;
    private javax.swing.JLabel DataMesin;
    private javax.swing.JLabel DataPerbaikan;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel Menu1;
    private javax.swing.JPanel Menu2;
    private javax.swing.JPanel Menu3;
    private javax.swing.JPanel Menu4;
    private javax.swing.JPanel Menu5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnMenu1;
    private javax.swing.JPanel pnMenu2;
    private javax.swing.JPanel pnMenu3;
    private javax.swing.JPanel pnMenu4;
    private javax.swing.JPanel pnMenu5;
    private javax.swing.JPanel pnMenu6;
    // End of variables declaration//GEN-END:variables
}
