/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package maintenance.service;


import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yusri
 */
public class menuPerbaikan extends javax.swing.JPanel {

    /**
     * Creates new form menuPerbaikan
     */
    public menuPerbaikan() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        tblPerbaikan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblPerbaikan.getTableHeader().setOpaque(false);
        tblPerbaikan.getTableHeader().setBackground(new Color(19, 71, 186));
        tblPerbaikan.getTableHeader().setForeground(new Color(255, 255, 255));
        
        // Pengaturan tinggi baris
        tblPerbaikan.setRowHeight(30);
        
        // Pengaturan font tabel
        tblPerbaikan.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        
        // Pengaturan warna latar belakang dan latar depan sel tabel
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(240, 240, 240)); // Warna latar belakang
        cellRenderer.setForeground(new Color(0, 0, 0)); // Warna teks
        tblPerbaikan.setDefaultRenderer(Object.class, cellRenderer);
        
        // Menambahkan margin pada sel tabel
        cellRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        loadData();
        comboMesin();
        comboMekanik();
        comboKaryawan();
    }
    
    
    private void comboMesin() {
        String SUrl, SUser, SPass, query;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            query = "SELECT * FROM mesin";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                cbMesin.addItem(rs.getString("nama_mesin"));
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    
    
    private void comboMekanik() {
        String SUrl, SUser, SPass, query;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            query = "SELECT * FROM mekanik";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                cbMekanik.addItem(rs.getString("nama_mekanik"));
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }
    
    private void comboKaryawan() {
        String SUrl, SUser, SPass, query;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            query = "SELECT * FROM karyawan";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                cbKaryawan.addItem(rs.getString("nama_karyawan"));
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cbMesin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbMekanik = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbKaryawan = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProblem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProblemsolving = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProblemclear = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerbaikan = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(74, 124, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(1046, 847));

        jPanel2.setBackground(new java.awt.Color(19, 71, 186));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 61));

        txtCari.setForeground(new java.awt.Color(153, 153, 153));
        txtCari.setText("Cari..");

        btnCari.setBackground(new java.awt.Color(19, 71, 186));
        btnCari.setForeground(new java.awt.Color(19, 71, 186));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintenance/service/cari.png"))); // NOI18N
        btnCari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perbaikan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSimpan.setBackground(new java.awt.Color(19, 71, 186));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nama Mesin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText(":");

        btnEdit.setBackground(new java.awt.Color(19, 71, 186));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(19, 71, 186));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        cbMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Mesin" }));
        cbMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nama Mekanik");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText(":");

        cbMekanik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Mekanik" }));
        cbMekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMekanikActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Nama Karyawan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText(":");

        cbKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Karyawan" }));
        cbKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKaryawanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Problem");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText(":");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Problem Solving");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText(":");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Problem Clear");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMesin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProblemclear, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtProblem, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(txtProblemsolving)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(cbMesin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(txtProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel5)
                        .addComponent(txtProblemsolving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(cbMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel6)
                        .addComponent(txtProblemclear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        tblPerbaikan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Mesin", "Nama Mekanik", "Nama Karyawan", "Problem", "Problem Solving", "Problem Clear"
            }
        ));
        jScrollPane1.setViewportView(tblPerbaikan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String ID;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        int notFound = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ID = txtCari.getText();
            if ("".equals(ID)) {
                JOptionPane.showMessageDialog(new JFrame(), "ID is require",
                        "Dialog",
                        JOptionPane.ERROR_MESSAGE);

            } else {
                String sql = "SELECT * FROM perbaikan WHERE id=" + ID;
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    cbMesin.setSelectedItem(rs.getString("nama_mesin"));
                    cbMekanik.setSelectedItem(rs.getString("nama_mekanik"));
                    cbKaryawan.setSelectedItem(rs.getString("nama_karyawan"));
                    txtProblem.setText(rs.getString("problem"));
                    txtProblemsolving.setText(rs.getString("problem_solving"));
                    txtProblemclear.setText(rs.getString("problem_clear"));
                    notFound = 1;
                    con.close();
                }
                if (notFound == 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "invalid ID",
                            "Dialog",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String namaMesin, namaMekanik, namaKaryawan, problem, problemSolving, problemClear, query;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            if (cbMesin.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Nama mesin harus di isi","Alert", JOptionPane.WARNING_MESSAGE);
            } else if (cbMekanik.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Nama Mekanik harus di isi","Alert",JOptionPane.WARNING_MESSAGE );
            } else if (cbKaryawan.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Nama Mekanik harus di isi","Alert",JOptionPane.WARNING_MESSAGE );
            } else if ("".equals(txtProblem.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Nama Problem harus di isi","Alert", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(txtProblemsolving.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Problem Solving harus di isi","Alert", JOptionPane.WARNING_MESSAGE);
            } else if ("".equals(txtProblemclear.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Problem Clear harus di isi","Alert", JOptionPane.WARNING_MESSAGE);

            } else {
                namaMesin = cbMesin.getSelectedItem().toString();
                namaMekanik = cbMekanik.getSelectedItem().toString();
                namaKaryawan = cbKaryawan.getSelectedItem().toString();
                problem = txtProblem.getText();
                problemSolving = txtProblemsolving.getText();
                problemClear = txtProblemclear.getText();
                query = "INSERT INTO perbaikan(nama_mesin,nama_mekanik,nama_karyawan,problem,problem_solving,problem_clear)"
                        + "VALUES('" + namaMesin + "', '" + namaMekanik + "','" + namaKaryawan + "' , '" + problem + "', '" + problemSolving + "', '" + problemClear + "')";

                st.execute(query);
                cbMesin.setSelectedIndex(0);
                cbMekanik.setSelectedIndex(0);
                cbKaryawan.setSelectedIndex(0);
                txtProblem.setText("");
                txtProblemsolving.setText("");
                txtProblemclear.setText("");
                showMessageDialog(null, "Data perbaikan berhasil disimpan!");
                loadData();
                con.close();
            }
        } catch (Exception e) {
            System.out.println("Error! " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String ID;
        int notFound = 0;
        String namaMesin, namaMekanik, namaKaryawan, problem, problemSolving, problemClear;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ID = txtCari.getText();
            if ("".equals(ID)) {
                JOptionPane.showMessageDialog(new JFrame(), "ID is require",
                        "Dialog",
                        JOptionPane.ERROR_MESSAGE);

            } else {
                String sql = "SELECT * FROM perbaikan WHERE id=" + ID;
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    notFound = 1;
                    namaMesin = cbMesin.getSelectedItem().toString();
                    namaMekanik = cbMekanik.getSelectedItem().toString();
                    namaKaryawan = cbKaryawan.getSelectedItem().toString();
                    problem = txtProblem.getText();
                    problemSolving = txtProblemsolving.getText();
                    problemClear = txtProblemclear.getText();
                    String sql2 = "UPDATE perbaikan SET nama_mesin='" + namaMesin +
                    "',nama_mekanik ='"+namaMekanik+ "',nama_karyawan ='"+namaKaryawan + "',problem ='"+problem + "',problem_solving ='"+problemSolving + 
                            "',problem_clear ='"+problemClear +"'  WHERE id="+ID;

                    st.executeUpdate(sql2);
                    cbMesin.setSelectedIndex(0);
                    cbMekanik.setSelectedIndex(0);
                    cbKaryawan.setSelectedIndex(0);
                    txtProblem.setText("");
                    txtProblemsolving.setText("");
                    txtProblemclear.setText("");
                    showMessageDialog(null, "Data Perbaikan berhasil diubah!");
                    loadData();
                    con.close();
                }
                if (notFound == 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "invalid ID",
                            "Dialog",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String ID;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        int notFound = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            ID = txtCari.getText();
            if ("".equals(ID)) {
                JOptionPane.showMessageDialog(new JFrame(), "ID is require",
                        "Dialog",
                        JOptionPane.ERROR_MESSAGE);

            } else {
                String sql = "SELECT * FROM perbaikan WHERE id=" + ID;
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    notFound = 1;
                    String sql2 = "DELETE FROM perbaikan WHERE id=" + ID;
                    st.executeUpdate(sql2);
                    cbMesin.setSelectedIndex(0);
                    cbMekanik.setSelectedIndex(0);
                    cbKaryawan.setSelectedIndex(0);
                    txtProblem.setText("");
                    txtProblemsolving.setText("");
                    txtProblemclear.setText("");
                    loadData();
                    con.close();
                    showMessageDialog(null, "Nilai has been Deleted");
                }
                if (notFound == 0) {
                    JOptionPane.showMessageDialog(new JFrame(), "invalid ID",
                            "Dialog",
                            JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesinActionPerformed

    private void cbMekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMekanikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMekanikActionPerformed

    private void cbKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKaryawan;
    private javax.swing.JComboBox<String> cbMekanik;
    private javax.swing.JComboBox<String> cbMesin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerbaikan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtProblem;
    private javax.swing.JTextField txtProblemclear;
    private javax.swing.JTextField txtProblemsolving;
    // End of variables declaration//GEN-END:variables

public final void loadData() {
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/mms_db";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Nama Mesin", "Nama Mekanik", "Nama Karyawan", "Problem", "Problem Solving", "Problem Clear"}, 0);
            tblPerbaikan.setModel(model);
            String sql = "SELECT * FROM perbaikan";
            java.sql.ResultSet rs = st.executeQuery(sql);
            String id, namaMesin, namaMekanik, namaKaryawan, problem, problemSolving, problemClear ;
            while (rs.next()) {
                id = rs.getString("id");
                namaMesin = rs.getString("nama_mesin");
                namaMekanik = rs.getString("nama_mekanik");
                namaKaryawan = rs.getString("nama_karyawan");
                problem = rs.getString("problem");
                problemSolving = rs.getString("problem_solving");
                problemClear = rs.getString("problem_clear");
                model.addRow(new Object[]{id, namaMesin, namaMekanik, namaKaryawan, problem, problemSolving, problemClear});
            }
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
}
}
